services:
  server:
    build: .
    ports:
      - "80:80"
    environment:
      DEBUG: 1
      REDIS_URL: redis://redis:6379
    volumes:
      - ./app:/code/app
    env_file:
      - .env
  redis:
    image: "redis:alpine"
